- apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    "{{ _autoff_repos }}"

- name: Ensure needed packages are present
  apt:
    name: "{{ item.name }}"
    default_release: "{{ item.default_release|default(omit) }}"
    state: latest
  with_items:
    "{{ _autoff_jenkins_pkgs }}"

- name: Ensure nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: reload nginx
