- name: "Ensure cowbuilder"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ _pbuilder_pkgs }}"

- name: Ensure sid chroot
  shell: git-pbuilder create
  args:
    creates: /var/cache/pbuilder/base.cow

- name: Ensure pbuilder sudoers
  copy:
    content: |
      %pbuilder ALL = (root) SETENV: NOPASSWD: /usr/sbin/cowbuilder, /usr/sbin/pbuilder
    dest: /etc/sudoers.d/pbuilder

- name: Ensure pbuilder group
  group:
    name: pbuilder

- name: Ensure pbuilder users are in pbuilder group
  user:
    name: "{{ item }}"
    group: pbuilder
    append: yes
  with_items:
    "{{ pbuilder_users }}"
  when: pbuilder_users is defined

- name: Ensure pbuilder hook dir
  file:
    path: "{{ pbuilder_hook_dir }}"
    state: directory
  when: pbuilder_hook_dir is defined

- name: Ensure pbuilder example hooks
  file:
    dest: "{{ pbuilder_hook_dir }}/{{ item }}"
    src: "/usr/share/doc/pbuilder/examples/{{ item }}"
    state: link
  with_items:
    "{{ pbuilder_example_hooks }}"
  when:
    - pbuilder_example_hooks is defined
    - pbuilder_hook_dir is defined